/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-06-05 12:26:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Sidebar2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1651191084430L));
    _jspx_dependants.put("jar:file:/C:/WebStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BBS/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cp);
      out.write("/css/main.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(\".alert\").addClass(\"in\").fadeOut(4500);\r\n");
      out.write("\t\r\n");
      out.write("\t/* swap open/close side menu icons */\r\n");
      out.write("\t$('[data-toggle=collapse]').click(function(){\r\n");
      out.write("\t      // toggle icon\r\n");
      out.write("\t  \t$(this).find(\"i\").toggleClass(\"glyphicon-chevron-right glyphicon-chevron-down\");\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html, body {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  font-family: \"Open Sans\";\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color: #ececec;\r\n");
      out.write("  color: #102c58;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("  -webkit-box-sizing: border-box;\r\n");
      out.write("  -moz-box-sizing: border-box;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("::-webkit-input-placeholder {\r\n");
      out.write("  color: #c3c3c3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("  font-size: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".u-list {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".u-input {\r\n");
      out.write("  outline: 0;\r\n");
      out.write("  border: 1px solid #d0d0d0;\r\n");
      out.write("  padding: 5px 10px;\r\n");
      out.write("  height: 35px;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  -webkit-border-radius: 10px;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background-clip: padding-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c-badge {\r\n");
      out.write("  font-size: 10px;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  min-width: 17px;\r\n");
      out.write("  padding: 5px 4px;\r\n");
      out.write("  border-radius: 100px;\r\n");
      out.write("  display: block;\r\n");
      out.write("  line-height: 0.7;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  white-space: nowrap;\r\n");
      out.write("  background-color: #f91605;\r\n");
      out.write("}\r\n");
      out.write(".c-badge--header-icon {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: -9px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tooltip {\r\n");
      out.write("  width: 120px;\r\n");
      out.write("}\r\n");
      out.write(".tooltip-inner {\r\n");
      out.write("  padding: 8px 10px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background-color: #051835;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write(".tooltip-arrow {\r\n");
      out.write("  border-right-color: #051835 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hamburger-toggle {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  border: 1px solid transparent;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  order: 1;\r\n");
      out.write("}\r\n");
      out.write(".hamburger-toggle [class*='bar-'] {\r\n");
      out.write("  display: block;\r\n");
      out.write("  background: #102c58;\r\n");
      out.write("  -webkit-transform: rotate(0deg);\r\n");
      out.write("  transform: rotate(0deg);\r\n");
      out.write("  -webkit-transition: .2s ease all;\r\n");
      out.write("  transition: .2s ease all;\r\n");
      out.write("  border-radius: 2px;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  width: 24px;\r\n");
      out.write("  margin-bottom: 4px;\r\n");
      out.write("}\r\n");
      out.write(".hamburger-toggle [class*='bar-']:nth-child(2) {\r\n");
      out.write("  width: 18px;\r\n");
      out.write("}\r\n");
      out.write(".hamburger-toggle [class*='bar-']:last-child {\r\n");
      out.write("  margin-bottom: 0;\r\n");
      out.write("  width: 12px;\r\n");
      out.write("}\r\n");
      out.write(".hamburger-toggle.is-opened {\r\n");
      out.write("  left: 3px;\r\n");
      out.write("}\r\n");
      out.write(".hamburger-toggle.is-opened [class*='bar-'] {\r\n");
      out.write("  background: #102c58;\r\n");
      out.write("}\r\n");
      out.write(".hamburger-toggle.is-opened .bar-top {\r\n");
      out.write("  -webkit-transform: rotate(45deg);\r\n");
      out.write("  transform: rotate(45deg);\r\n");
      out.write("  -webkit-transform-origin: 15% 15%;\r\n");
      out.write("  transform-origin: 15% 15%;\r\n");
      out.write("}\r\n");
      out.write(".hamburger-toggle.is-opened .bar-mid {\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("}\r\n");
      out.write(".hamburger-toggle.is-opened .bar-bot {\r\n");
      out.write("  -webkit-transform: rotate(45deg);\r\n");
      out.write("  transform: rotate(-45deg);\r\n");
      out.write("  -webkit-transform-origin: 15% 95%;\r\n");
      out.write("  transform-origin: 15% 95%;\r\n");
      out.write("  width: 24px;\r\n");
      out.write("}\r\n");
      out.write(".hamburger-toggle:focus {\r\n");
      out.write("  outline-width: 0;\r\n");
      out.write("}\r\n");
      out.write(".hamburger-toggle:hover [class*='bar-'] {\r\n");
      out.write("  background: #f5642d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-icons-group {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  order: 3;\r\n");
      out.write("  margin-left: auto;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  border-left: 1px solid #cccccc;\r\n");
      out.write("}\r\n");
      out.write(".header-icons-group .c-header-icon:last-child {\r\n");
      out.write("  border-right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c-header-icon {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 70px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  line-height: 1;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-right: 1px solid #cccccc;\r\n");
      out.write("}\r\n");
      out.write(".c-header-icon i {\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  line-height: 40px;\r\n");
      out.write("}\r\n");
      out.write(".c-header-icon--in-circle {\r\n");
      out.write("  border: 1px solid #d0d0d0;\r\n");
      out.write("  border-radius: 100%;\r\n");
      out.write("}\r\n");
      out.write(".c-header-icon:hover i {\r\n");
      out.write("  color: #f5642d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-header {\r\n");
      out.write("  padding-left: 70px;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  z-index: 10;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background: #ffffff;\r\n");
      out.write("  -webkit-transition: padding 0.5s ease-in-out;\r\n");
      out.write("  -moz-transition: padding 0.5s ease-in-out;\r\n");
      out.write("  -ms-transition: padding 0.5s ease-in-out;\r\n");
      out.write("  -o-transition: padding 0.5s ease-in-out;\r\n");
      out.write("  transition: padding 0.5s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".l-header__inner {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  height: 70px;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: stretch;\r\n");
      out.write("  border-bottom: 1px solid;\r\n");
      out.write("  border-color: #cccccc;\r\n");
      out.write("}\r\n");
      out.write(".sidebar-is-expanded .l-header {\r\n");
      out.write("  padding-left: 220px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c-search {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 350px;\r\n");
      out.write("}\r\n");
      out.write(".c-search__input {\r\n");
      out.write("  border-top-right-radius: 0px;\r\n");
      out.write("  border-bottom-right-radius: 0px;\r\n");
      out.write("  border-right: 0;\r\n");
      out.write("  flex-basis: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  padding: 0 20px;\r\n");
      out.write("  -webkit-transition: all 0.3s ease-in-out;\r\n");
      out.write("  -moz-transition: all 0.3s ease-in-out;\r\n");
      out.write("  -ms-transition: all 0.3s ease-in-out;\r\n");
      out.write("  -o-transition: all 0.3s ease-in-out;\r\n");
      out.write("  transition: all 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c-dropdown {\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  display: none;\r\n");
      out.write("  width: 300px;\r\n");
      out.write("  top: 30px;\r\n");
      out.write("  right: -40px;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  min-height: 300px;\r\n");
      out.write("  border: 1px solid #d0d0d0;\r\n");
      out.write("  -webkit-border-radius: 10px;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background-clip: padding-box;\r\n");
      out.write("  -webkit-box-shadow: 0px 5px 14px -1px #cecece;\r\n");
      out.write("  -moz-box-shadow: 0px 5px 14px -1px #cecece;\r\n");
      out.write("  box-shadow: 0px 5px 14px -1px #cecece;\r\n");
      out.write("  -webkit-transition: all 0.3s ease-in-out;\r\n");
      out.write("  -moz-transition: all 0.3s ease-in-out;\r\n");
      out.write("  -ms-transition: all 0.3s ease-in-out;\r\n");
      out.write("  -o-transition: all 0.3s ease-in-out;\r\n");
      out.write("  transition: all 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-sidebar {\r\n");
      out.write("  width: 70px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  z-index: 10;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  background: #102c58;\r\n");
      out.write("  -webkit-transition: width 0.5s ease-in-out;\r\n");
      out.write("  -moz-transition: width 0.5s ease-in-out;\r\n");
      out.write("  -ms-transition: width 0.5s ease-in-out;\r\n");
      out.write("  -o-transition: width 0.5s ease-in-out;\r\n");
      out.write("  transition: width 0.5s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".l-sidebar .logo {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 70px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  background-color: #051835;\r\n");
      out.write("}\r\n");
      out.write(".l-sidebar .logo .logo__txt {\r\n");
      out.write("  font-size: 26px;\r\n");
      out.write("  line-height: 1;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write(".l-sidebar__content {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".sidebar-is-expanded .l-sidebar {\r\n");
      out.write("  width: 220px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c-menu > ul {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  max-width: 100%;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item__inner {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: row;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  min-height: 60px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  -webkit-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -moz-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -ms-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -o-transition: all 0.5s ease-in-out;\r\n");
      out.write("  transition: all 0.5s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item__inner:before {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  content: \" \";\r\n");
      out.write("  height: 0;\r\n");
      out.write("  width: 2px;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  margin-top: -18px;\r\n");
      out.write("  background-color: #5f9cfd;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  -webkit-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -moz-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -ms-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -o-transition: all 0.5s ease-in-out;\r\n");
      out.write("  transition: all 0.5s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item.is-active .c-menu__item__inner {\r\n");
      out.write("  border-left-color: #5f9cfd;\r\n");
      out.write("  background-color: #1e3e6f;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item.is-active .c-menu__item__inner i {\r\n");
      out.write("  color: #5f9cfd;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item.is-active .c-menu__item__inner .c-menu-item__title span {\r\n");
      out.write("  color: #5f9cfd;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item.is-active .c-menu__item__inner:before {\r\n");
      out.write("  height: 36px;\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item:not(.is-active):hover .c-menu__item__inner {\r\n");
      out.write("  background-color: #f5642d;\r\n");
      out.write("  border-left-color: #f5642d;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item i {\r\n");
      out.write("  flex: 0 0 70px;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  font-weight: normal;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  -webkit-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -moz-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -ms-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -o-transition: all 0.5s ease-in-out;\r\n");
      out.write("  transition: all 0.5s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item .c-menu-item__expand {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  left: 100px;\r\n");
      out.write("  padding-right: 20px;\r\n");
      out.write("  margin-left: auto;\r\n");
      out.write("  -webkit-transition: all 1s ease-in-out;\r\n");
      out.write("  -moz-transition: all 1s ease-in-out;\r\n");
      out.write("  -ms-transition: all 1s ease-in-out;\r\n");
      out.write("  -o-transition: all 1s ease-in-out;\r\n");
      out.write("  transition: all 1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".sidebar-is-expanded .c-menu > ul .c-menu__item .c-menu-item__expand {\r\n");
      out.write("  left: 0px;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item .c-menu-item__title {\r\n");
      out.write("  flex-basis: 100%;\r\n");
      out.write("  padding-right: 10px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  left: 220px;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  -webkit-transition: all 0.7s ease-in-out;\r\n");
      out.write("  -moz-transition: all 0.7s ease-in-out;\r\n");
      out.write("  -ms-transition: all 0.7s ease-in-out;\r\n");
      out.write("  -o-transition: all 0.7s ease-in-out;\r\n");
      out.write("  transition: all 0.7s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item .c-menu-item__title span {\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  white-space: nowrap;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  text-overflow: ellipsis;\r\n");
      out.write("  -webkit-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -moz-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -ms-transition: all 0.5s ease-in-out;\r\n");
      out.write("  -o-transition: all 0.5s ease-in-out;\r\n");
      out.write("  transition: all 0.5s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".sidebar-is-expanded .c-menu > ul .c-menu__item .c-menu-item__title {\r\n");
      out.write("  left: 0px;\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item .c-menu__submenu {\r\n");
      out.write("  background-color: #051835;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item .c-menu__submenu li {\r\n");
      out.write("  padding-bottom: 15px;\r\n");
      out.write("  margin-bottom: 15px;\r\n");
      out.write("  border-bottom: 1px solid;\r\n");
      out.write("  border-color: #072048;\r\n");
      out.write("  color: #5f9cfd;\r\n");
      out.write("}\r\n");
      out.write(".c-menu > ul .c-menu__item .c-menu__submenu li:last-child {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  border: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("main.l-main {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  padding: 70px 0 0 70px;\r\n");
      out.write("  -webkit-transition: padding 0.5s ease-in-out;\r\n");
      out.write("  -moz-transition: padding 0.5s ease-in-out;\r\n");
      out.write("  -ms-transition: padding 0.5s ease-in-out;\r\n");
      out.write("  -o-transition: padding 0.5s ease-in-out;\r\n");
      out.write("  transition: padding 0.5s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("main.l-main .content-wrapper {\r\n");
      out.write("  padding: 25px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write("main.l-main .content-wrapper .page-content {\r\n");
      out.write("  border-top: 1px solid #d0d0d0;\r\n");
      out.write("  padding-top: 25px;\r\n");
      out.write("}\r\n");
      out.write("main.l-main .content-wrapper--with-bg .page-content {\r\n");
      out.write("  background: #fff;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  border: 1px solid #d0d0d0;\r\n");
      out.write("  padding: 25px;\r\n");
      out.write("}\r\n");
      out.write("main.l-main .page-title {\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("  margin-top: 0;\r\n");
      out.write("  margin-bottom: 25px;\r\n");
      out.write("}\r\n");
      out.write(".sidebar-is-expanded main.l-main {\r\n");
      out.write("  padding-left: 220px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<body class=\"sidebar-is-reduced\">\r\n");
      out.write("  <header class=\"l-header\">\r\n");
      out.write("    <div class=\"l-header__inner clearfix\">\r\n");
      out.write("      <div class=\"c-header-icon js-hamburger\">\r\n");
      out.write("        <div class=\"hamburger-toggle\"><span class=\"bar-top\"></span><span class=\"bar-mid\"></span><span class=\"bar-bot\"></span></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"c-header-icon has-dropdown\"><span class=\"c-badge c-badge--header-icon animated shake\">87</span><i class=\"fa fa-bell\"></i>\r\n");
      out.write("        <div class=\"c-dropdown c-dropdown--notifications\">\r\n");
      out.write("          <div class=\"c-dropdown__header\"></div>\r\n");
      out.write("          <div class=\"c-dropdown__content\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"c-search\">\r\n");
      out.write("        <input class=\"c-search__input u-input\" placeholder=\"Search...\" type=\"text\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"header-icons-group\">\r\n");
      out.write("        <div class=\"c-header-icon basket\"><span class=\"c-badge c-badge--header-icon animated shake\">12</span><i class=\"fa fa-shopping-basket\"></i></div>\r\n");
      out.write("        <div class=\"c-header-icon logout\"><i class=\"fa fa-power-off\"></i></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <div class=\"l-sidebar\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("      <div class=\"logo__txt\">D</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"l-sidebar__content\">\r\n");
      out.write("      <nav class=\"c-menu js-menu\">\r\n");
      out.write("        <ul class=\"u-list\">\r\n");
      out.write("          <li class=\"c-menu__item is-active\" data-toggle=\"tooltip\" title=\"Flights\">\r\n");
      out.write("            <div class=\"c-menu__item__inner\"><i class=\"fa fa-plane\"></i>\r\n");
      out.write("              <div class=\"c-menu-item__title\"><span>Flights</span></div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"c-menu__item has-submenu\" data-toggle=\"tooltip\" title=\"Modules\">\r\n");
      out.write("            <div class=\"c-menu__item__inner\"><i class=\"fa fa-puzzle-piece\"></i>\r\n");
      out.write("              <div class=\"c-menu-item__title\"><span>Modules</span></div>\r\n");
      out.write("              <div class=\"c-menu-item__expand js-expand-submenu\"><i class=\"fa fa-angle-down\"></i></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"c-menu__submenu u-list\">\r\n");
      out.write("              <li>Payments</li>\r\n");
      out.write("              <li>Maps</li>\r\n");
      out.write("              <li>Notifications</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"c-menu__item has-submenu\" data-toggle=\"tooltip\" title=\"Statistics\">\r\n");
      out.write("            <div class=\"c-menu__item__inner\"><i class=\"fa fa-bar-chart\"></i>\r\n");
      out.write("              <div class=\"c-menu-item__title\"><span>Statistics</span></div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"c-menu__item has-submenu\" data-toggle=\"tooltip\" title=\"Gifts\">\r\n");
      out.write("            <div class=\"c-menu__item__inner\"><i class=\"fa fa-gift\"></i>\r\n");
      out.write("              <div class=\"c-menu-item__title\"><span>Gifts</span></div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"c-menu__item has-submenu\" data-toggle=\"tooltip\" title=\"Settings\">\r\n");
      out.write("            <div class=\"c-menu__item__inner\"><i class=\"fa fa-cogs\"></i>\r\n");
      out.write("              <div class=\"c-menu-item__title\"><span>Settings</span></div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("<main class=\"l-main\">\r\n");
      out.write("  <div class=\"content-wrapper content-wrapper--with-bg\">\r\n");
      out.write("    <h1 class=\"page-title\">Dashboard</h1>\r\n");
      out.write("    <div class=\"page-content\">Content goes here</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</main>\r\n");
      out.write("<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script><script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script><script src='https://use.fontawesome.com/2188c74ac9.js'></script><script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js'></script>\r\n");
      out.write("<script >\"use strict\";\r\n");
      out.write("\r\n");
      out.write("var Dashboard = function () {\r\n");
      out.write("\tvar global = {\r\n");
      out.write("\t\ttooltipOptions: {\r\n");
      out.write("\t\t\tplacement: \"right\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tmenuClass: \".c-menu\"\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar menuChangeActive = function menuChangeActive(el) {\r\n");
      out.write("\t\tvar hasSubmenu = $(el).hasClass(\"has-submenu\");\r\n");
      out.write("\t\t$(global.menuClass + \" .is-active\").removeClass(\"is-active\");\r\n");
      out.write("\t\t$(el).addClass(\"is-active\");\r\n");
      out.write("\r\n");
      out.write("\t\t// if (hasSubmenu) {\r\n");
      out.write("\t\t// \t$(el).find(\"ul\").slideDown();\r\n");
      out.write("\t\t// }\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar sidebarChangeWidth = function sidebarChangeWidth() {\r\n");
      out.write("\t\tvar $menuItemsTitle = $(\"li .menu-item__title\");\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"body\").toggleClass(\"sidebar-is-reduced sidebar-is-expanded\");\r\n");
      out.write("\t\t$(\".hamburger-toggle\").toggleClass(\"is-opened\");\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(\"body\").hasClass(\"sidebar-is-expanded\")) {\r\n");
      out.write("\t\t\t$('[data-toggle=\"tooltip\"]').tooltip(\"destroy\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('[data-toggle=\"tooltip\"]').tooltip(global.tooltipOptions);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\treturn {\r\n");
      out.write("\t\tinit: function init() {\r\n");
      out.write("\t\t\t$(\".js-hamburger\").on(\"click\", sidebarChangeWidth);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\".js-menu li\").on(\"click\", function (e) {\r\n");
      out.write("\t\t\t\tmenuChangeActive(e.currentTarget);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('[data-toggle=\"tooltip\"]').tooltip(global.tooltipOptions);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("}();\r\n");
      out.write("\r\n");
      out.write("Dashboard.init();\r\n");
      out.write("//# sourceURL=pen.js\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
